"use strict"; //treat all js code as newer version(with class ,mpdule,arrowfunction as the old java script did  not have thos so we strict to usse only newer js)
//alert(3+3) //we are using node js not browser

// code readability should be higher
// tc39 ECMA Script [set the standard] and mdn used for reading documentation
let name = "Mehar"
let age=20
let isLoggedIn = false
//number=>2 to power 53
// bigint
// string->""
// boolean=>true/false
// null ->standalone value(special type)
// undefined =>
// symbol =>unique

// object
console.log(typeof undefined);//op undefined cause it is type
console.log(typeof null);//object
