const accountId=144553
let accountEmail="mehar@google.com"
var accountPassword="12223"
// [prefer not to use var due to block scope isuee cause it change at all place once you done changes in it ]
accountCity="jaipur"
 let accountState;
//when you only declare a variable without assigning a value JS  take it as undefined 

// accountId=2//not allowed
accountEmail="hisih@n.com"
accountPassword="6767"
accountCity="lucknow"
console.log(accountState);


console.log(accountEmail);
console.table([accountCity,accountEmail,accountPassword]);


