 let score= "33abd"
//  const {score}=req.body
// console.log(typeof score);
// console.log(typeof(score));
 let valueInNumber= Number (score)
 
//  console.log(typeof valueInNumber );
//  console.log(valueInNumber);
//  "33" convert into->33
// "33abd"=>NaN
//true=>1; false=>0
let isLoggedIn ="mehar"
let booleanIsLoggedIn= Boolean(isLoggedIn) ;
// console.log(booleanIsLoggedIn)
// 1=>true 0=>false
// ""=>false empty string=>flase
// "mehar"=>true
let someNumber=33
// let stringNumber=String(someNumber)
// console.log( typeof stringNumber);


// operations----------------------------------
let value=3
let ngValue= -value
// console.log(ngValue);
console.log(2+2);
console.log(2-2);
console.log(2*2);
console.log(2**2);

console.log(2/2);
console.log(2%2);
 let str1="hello"
 let str2=" Mehar"
 let str3= str1+ str2
 console.log(str3);
 console.log("1"+2);
 console.log(1 +"2" +2);
 console.log(1 +"2" +"2");
 console.log(1 +2 +"2");
 //when  num in str in start it take whole value as a string
 //when  num in str in end it take only that value as a string and starting value as numb
 
console.log(+true);
console.log(+"");

let num1, num2 ,num3;
num1= num2= num3= 2+2 //bad practice
let gameCounter=100
gameCounter++;
console.log(gameCounter);
 
 


