const name="mehar"
const repocount=30
// console.log(name+ repocount + "value");
console.log(`hello my name is ${name} and my repo count is ${repocount}`);
const gameName=new String ('Meharrr-ff')
console.log(gameName[0]);
console.log(gameName.__proto__);
console.log(gameName.length);
console.log(gameName.toLocaleLowerCase());
console.log(gameName.charAt(2));
console.log(gameName.indexOf("r"));

 const newString=gameName.substring(0,5)
 console.log(newString);
 console.log("slice");
 
 const anotherString =gameName.slice(-7,4)
 console.log(anotherString);
 //trim removes extra spaces
 const newStr="  mehar    "
 console.log(newStr);
 console.log(newStr.trim());
 console.log(newStr.trimEnd());//removes end space
 console.log(newStr.trimStart());//removes start space
 const url="https://nxncujdh//bndhsbb%45nhd"
 console.log(url.replace('%45', "-"))
console.log( url.includes("mehar"))
console.log( gameName.split("-"))//split based om - convert into array



 



