 let score= "33abd"
//  const {score}=req.body
console.log(typeof score);
console.log(typeof(score));
 let valueInNumber= Number (score)
 
 console.log(typeof valueInNumber );
 console.log(valueInNumber);
//  "33" convert into->33
// "33abd"=>NaN
//true=>1; false=>0
let isLoggedIn ="mehar"
let booleanIsLoggedIn= Boolean(isLoggedIn) ;
console.log(booleanIsLoggedIn)
// 1=>true 0=>false
// ""=>false empty string=>flase
// "mehar"=>true
let someNumber=33
let stringNumber=String(someNumber)
console.log( typeof stringNumber);
